spring:
    config:
        import: secrets.yml
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
    jpa:
        hibernate:
            ddl-auto: update #create update none
            use-new-id-generator-mappings: false

jwt:
    secret: ${JWT_SECRET}